# Generated by Django 3.0.4 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200307_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_list',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
