# Generated by Django 3.0.4 on 2020-03-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200319_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_array',
        ),
    ]
