# Generated by Django 3.0.4 on 2020-03-19 04:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_event_date_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[], size=365),
            preserve_default=False,
        ),
    ]
