# Generated by Django 3.0.4 on 2020-03-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='times',
        ),
    ]
