# Generated by Django 3.0.4 on 2020-04-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
