# Generated by Django 3.0.4 on 2020-03-19 03:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_event_date_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
