# Generated by Django 3.0.4 on 2020-03-19 03:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_event_date_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=365),
        ),
    ]
