# Generated by Django 3.0.4 on 2020-03-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_event_date_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_list',
        ),
    ]
