# Generated by Django 3.0.4 on 2020-03-19 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_event_date_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=[], size=7),
            preserve_default=False,
        ),
    ]
