# Generated by Django 3.0.4 on 2020-03-19 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_event_day_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=200),
            preserve_default=False,
        ),
    ]
