# Generated by Django 3.0.4 on 2020-04-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_times_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('snd_hash', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='times',
            name='name',
        ),
    ]
