# Generated by Django 3.0.3 on 2020-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(max_length=100),
        ),
    ]
