# Generated by Django 3.0.3 on 2020-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='earliest',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='latest',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='repeating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
