# Generated by Django 3.0.4 on 2020-03-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200306_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeating',
            field=models.BooleanField(),
        ),
    ]
